# Generated by Django 4.0 on 2022-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.TextField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.TextField(blank=True, max_length=10)),
                ('patient_location', models.TextField(blank=True, max_length=50)),
                ('patient_date_of_visit', models.DateTimeField(auto_now_add=True)),
                ('patient_reason_to_visit', models.TextField(blank=True, max_length=25)),
            ],
        ),
    ]
